### ISSUE TITLE
feat: 希望提供开放API以便后人填坑，网页版真的很不方便

### ISSUE THREAD

**Issue by chunibyo-wly** [PointStoneTeam/cugapp#1]

**Comment by cugxuan** [comment]
> _No description provided._

谢谢，不过这个应该暂时没人维护了😌不知道还能不能用、

**Comment by chenlx0** [comment]
目前学校大部分面向学生的服务类网站都封闭了外网访问，提供公网环境下的开放 API 不太现实，也可能违反相关法律法规。

**Comment by chunibyo-wly** [comment]
好的，谢谢楼上👍
